version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Zipping Lambda functions...
      - zip -r latest-backend.zip src/handlers/ node_modules package.json

  post_build:
    commands:
      - echo Uploading latest-backend.zip to S3...
      - aws s3 cp latest-backend.zip s3://my-backend-lambda-code-bucket/

artifacts:
  files:
    - latest-backend.zip
